Debugging yaml file

diff --git a/.github/workflows/run-data-processing.yml b/.github/workflows/run-data-processing.yml
--- a/.github/workflows/run-data-processing.yml
+++ b/.github/workflows/run-data-processing.yml
@@ -37,35 +37,26 @@ jobs:
           echo "Deleted files: $deleted_files"
         fi
 
-    # - name: Delete previous files with prefix 'quakes_'
-    #   run: |
-    #     echo "Deleting previous parquet files..."
-    #     DELETED_FILES=$(find data/ -name 'quakes_*.parquet' -exec rm {} \; -print)
-    #     if [ -z "$DELETED_FILES" ]; then
-    #       echo "No files with prefix 'quakes_' found."
-    #     else
-    #       echo "Deleted files: $DELETED_FILES"
-    #     fi
-    #
-    # - name: Run data processing script
-    #   run: |
-    #     echo "Starting data processing script..."
-    #     set -e 
-    #     python src/data_processing.py || { echo "Data processing failed"; exit 1; }
-    #     echo "Data processing completed successfully."
-    #
-    # - name: Commit and push the processed data
-    #   if: success() 
-    #   run: |
-    #     echo "Committing and pushing processed data..."
-    #     git config --global user.name "github actions"
-    #     git config --global user.email "actions@github.com"
-    #     git add data/
-    #     git diff --quiet && git diff --staged --quiet || git commit -m "Update processed data on $(date +'%y-%m-%d %H:%M:%S')"
-    #     git push || { echo "Git push failed"; exit 1; }
-    #   env:
-    #     github_token: ${{ secrets.github_token }}
-    #
+
+    - name: Run data processing script
+      run: |
+        echo "Starting data processing script..."
+        set -e 
+        python src/data_processing.py || { echo "Data processing failed"; exit 1; }
+        echo "Data processing completed successfully."
+
+    - name: Commit and push the processed data
+      if: success() 
+      run: |
+        echo "Committing and pushing processed data..."
+        git config --global user.name "github actions"
+        git config --global user.email "actions@github.com"
+        git add data/
+        git diff --quiet && git diff --staged --quiet || git commit -m "Update processed data on $(date +'%y-%m-%d %H:%M:%S')"
+        git push || { echo "Git push failed"; exit 1; }
+      env:
+        github_token: ${{ secrets.github_token }}
+
     # - name: Send Slack notification on success
     #   if: success()
     #   uses: 8398a7/action-slack@v3
