Debugging yaml file

diff --git a/.github/workflows/run-data-processing.yml b/.github/workflows/run-data-processing.yml
--- a/.github/workflows/run-data-processing.yml
+++ b/.github/workflows/run-data-processing.yml
@@ -22,27 +22,29 @@ jobs:
       run: |
         echo "Installing dependencies..."
         python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then 
-          pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }
+        if [ -f requirements.txt ]; 
+        then 
+          pip install -r requirements.txt 
+    #   || { echo "Dependency installation failed"; exit 1; }
         fi
-
-    - name: Delete previous files with prefix 'quakes_'
-      run: |
-        echo "Deleting previous parquet files..."
-        DELETED_FILES=$(find data/ -name 'quakes_*.parquet' -exec rm {} \; -print)
-        if [ -z "$DELETED_FILES" ]; then
-          echo "No files with prefix 'quakes_' found."
-        else
-          echo "Deleted files: $DELETED_FILES"
-        fi
-
-    - name: Run data processing script
-      run: |
-        echo "Starting data processing script..."
-        set -e 
-        python src/data_processing.py || { echo "Data processing failed"; exit 1; }
-        echo "Data processing completed successfully."
-
+    #
+    # - name: Delete previous files with prefix 'quakes_'
+    #   run: |
+    #     echo "Deleting previous parquet files..."
+    #     DELETED_FILES=$(find data/ -name 'quakes_*.parquet' -exec rm {} \; -print)
+    #     if [ -z "$DELETED_FILES" ]; then
+    #       echo "No files with prefix 'quakes_' found."
+    #     else
+    #       echo "Deleted files: $DELETED_FILES"
+    #     fi
+    #
+    # - name: Run data processing script
+    #   run: |
+    #     echo "Starting data processing script..."
+    #     set -e 
+    #     python src/data_processing.py || { echo "Data processing failed"; exit 1; }
+    #     echo "Data processing completed successfully."
+    #
     # - name: Commit and push the processed data
     #   if: success() 
     #   run: |
